Book.id=123
Book.title=Develop with Java
Book.price=23423
Book.authors=Rajat, Deepansh, Yash

Student.sid=23
Student.sname=Rajat
Student.course=java

Course.courseId=123
Course.courseName=Java
Course.courseCost=456